# Principles of Artificial Inteligence

## The Role of Python in AI

### A Brief Introduction to the NumPy Library

The NumPy library will play a major role in this book, so it is worth exploring it further. The way to call NumPy to our program is through:

In [3]:
import numpy as np  # we're importing it as creating an alias

NumPy comes in handy with its data structures like vectors and matrices since Python does not come with built-ins for them:

In [9]:
np.array([1, 3, 5, 7])

array([1, 3, 5, 7])

In [12]:
my_matrix = np.mat([[1, 2], [3, 3]])
my_matrix

matrix([[1, 2],
        [3, 3]])

We can perform many operations with matrices. These include addition, subtraction, and multiplication.

In [14]:
my_matrix + my_matrix

matrix([[2, 4],
        [6, 6]])

In [15]:
my_matrix - my_matrix

matrix([[0, 0],
        [0, 0]])

In [18]:
my_matrix * my_matrix

matrix([[ 7,  8],
        [12, 15]])

The multiplication of matrices follows the rules of linear algebra. To get the (i,j)th element of the matrix, you compute the dot (scalar) product on the ith row of the matrix with the jth column. The scalar product of two vectors is the sum of the product of their corresponding coordinates. Another thing that's useful sometimes is calculating a matrix determinant, a property of square matrices:

In [20]:
np.linalg.det(my_matrix)
# there is an error associated because numpy does it as a floating point operation...
# however if we know the matrix is 100% made of integers we can cast it to an integer

-3.0000000000000004

Other common usage is transposing a matrix (switching columns with lines):

In [21]:
np.matrix.transpose(my_matrix)

matrix([[1, 3],
        [2, 3]])